### ISSUE TITLE
File sizes

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#243]
After conversation with @joeytalbot I've checked file sizes associated with a full build and they are indeed huge, topping out at over 1 GB RDS files as shown below. Should we try to reduce these sizes before saving?

![image](https://github.com/nptscot/npt/assets/1825120/330e1bcf-df74-4fcf-a96c-05bc545b17fb)

**Comment by mem48** [comment]
I think the main reason is that we do everything at the segment level, which results in massive duplication. But the only thing that required segment-level data is the quietness and gradient maps.



Fix would be

1) Minor tweak to `cyclestreets::json2sf_cs`  so the `segments = TRUE/FALSE`  option adds a `both` option.
2) Split the workflow so that the routes are passed through the current workflow (should only require minior changes). The segments pass through a new workflow that makes rnets for just quietness and gradient.
3) Merge the rnets from the two workflows.

I think this should be quite easy. It would also being other speed improvements such as when building the rnets not needing to calculate variables that are then immediately thrown away.

**Comment by Robinlovelace** [comment]
Happy for you to give that a bash @mem48 but is it a priority?

I plan to refactor so that we never need all routes to be loaded into memory at the same time.

**Comment by mem48** [comment]
I see no reason not to do both. But my solution should scale better, as it fundamentally reduces the size of all the datasets downstream of routing by around 20x. While yours probably just cuts peak memory usage by 4x.

**Comment by mem48** [comment]
PR for step 1 Submitted

**Comment by Robinlovelace** [comment]
Let's give both a bash and see which ones work. How do you get the rnet values for quietness and gradient though?

**Comment by mem48** [comment]
You still make the segments and make a rnet from them, but only for quietness and gradient. This means you can go straight from routing --> rnet without going through the uptake and other stages.
