### ISSUE TITLE
Update cn aggregation and geometries

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#537]
We should make the cn geometries have the following characteristics:

- [x] No breaks between cn junctions (may need more breaks or aggregations)
- [x] Take the average cycling potential in joined segments
- [x] Output as linestrings

**Comment by wangzhao0217** [comment]
Hi @Robinlovelace @dabreegster , Please review the latest version of the coherent network example, which has been updated as per our discussion.
![image](https://github.com/user-attachments/assets/a222f4c8-c1ff-4920-b6f1-0085dc080f47)
https://github.com/nptscot/npt/releases/download/osm_example/city_of_edinburgh_2024-09-01_4_coherent_network.geojson

**Comment by dabreegster** [comment]
This is an improvement, but there are still MultiLineStrings left in the output, like 
![image](https://github.com/user-attachments/assets/a05bf519-499b-4905-a829-06b862bcb01b)
and cases where I'd expect the linestring to be longer, because it's degree 2 at one end
![image](https://github.com/user-attachments/assets/134273a1-3b42-4f21-bbe5-6e0c80e41b31)

There were 3 things we've talked about. I assume this is only tackling the first?

1) Split the CN into individual LineStrings that represent something a user would meaningfully want to work with (so hundreds of tiny segments not useful)
2) Use OSM instead of OS
3) Preserve OSM node or way or both IDs in order on each LineString, so we can avoid map-matching hassles

**Comment by wangzhao0217** [comment]
Hi @dabreegster, Sorry for overlooking the issue with MultiLineStrings. I have updated the GeoJSON.
https://github.com/nptscot/npt/releases/download/osm_example/city_of_edinburgh_2024-09-01_4_coherent_network.geojson
Regarding the short path, I will take a look, but there isn't a quick solution at the moment.
As for using OSM instead of OS, I will need confirmation from Sustran before proceeding with the change. This will be a top priority to confirm next week. Once we have the confirmation, I will provide the OSM data based on CN.

```r
cn = sf::st_read("city_of_edinburgh_2024-09-01_4_coherent_network.geojson") 
geometry_type = sf::st_geometry_type(cn)
print(unique(geometry_type))
[1] LINESTRING
18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE
```

**Comment by Robinlovelace** [comment]
Good job updating the geomtries, does that work for you @dabreegster ?
