### ISSUE TITLE
Segregated link with 4000+ motor traffic

### ISSUE THREAD

**Issue by juanfonsecaLS1** [nptscot/npt#559]
@wangzhao0217, I just detected that one segregated path has been assigned a motor flow of 4000+, which is the flow of the A901 road which runs parallel. 

![image](https://github.com/user-attachments/assets/b36946e6-490b-4351-ada7-a554756a002b)

**Comment by juanfonsecaLS1** [comment]
This is where the link is https://nptscot.github.io/#/clos/#16.54/55.980621/-3.219636

**Comment by Robinlovelace** [comment]
Heads-up @juanfonsecaLS1 I think this is a feature not a bug: sometimes it's useful to know the traffic level of roads running parallel to segregated along-road cycleways. We'll change it so that only Off Road Track infrastructure is hardcoded to 0. The traffic on that segment will affect users (e.g. noise, stress).

**Comment by Robinlovelace** [comment]
As shown here, it's not a 0 traffic place:

![image](https://github.com/user-attachments/assets/97d29a8d-ec45-4f9e-8e5e-5ad822052989)

**Comment by Robinlovelace** [comment]
If you find any other examples where the traffic values are questionable, let us know :pray:
